# -*- coding: utf-8 -*-
"""MorseCodeTranslator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yf2mVN1PRuMgSH0o_U7NjHPhwm7tmm0d
"""

#Dictionary  morse code
MORSE_CODE_DICT = { 'A':'.-', 'B':'-...',
                    'C':'-.-.', 'D':'-..', 'E':'.',
                    'F':'..-.', 'G':'--.', 'H':'....',
                    'I':'..', 'J':'.---', 'K':'-.-',
                    'L':'.-..', 'M':'--', 'N':'-.',
                    'O':'---', 'P':'.--.', 'Q':'--.-',
                    'R':'.-.', 'S':'...', 'T':'-',
                    'U':'..-', 'V':'...-', 'W':'.--',
                    'X':'-..-', 'Y':'-.--', 'Z':'--..',
                    '1':'.----', '2':'..---', '3':'...--',
                    '4':'....-', '5':'.....', '6':'-....',
                    '7':'--...', '8':'---..', '9':'----.',
                    '0':'-----', ', ':'--..--', '.':'.-.-.-',
                    '?':'..--..', '/':'-..-.', '-':'-....-',
                    '(':'-.--.', ')':'-.--.-'}

# Function to encrypt the string
# according to the morse code chart
def encrypt(message):
    cipher = ''
    for letter in message:
        if letter != ' ':


            cipher += MORSE_CODE_DICT[letter] + ' '
        else:

            cipher += ' '

    return cipher


def decrypt(message):

    # extra space added at the end to access the
    # last morse code
    message += ' '

    decipher = ''
    stext = ''
    for letter in message:


        if (letter != ' '):

            i = 0

            stext += letter


        else:

            i += 1

            if i == 2 :


                decipher += ' '
            else:


                decipher += list(MORSE_CODE_DICT.keys())[list(MORSE_CODE_DICT
                .values()).index(stext)]
                stext = ''

    return decipher


message = input("Type your sentence").upper()
user_request = input("do you want to Encode / Decode").lower()

if user_request == 'decode':
  result = decrypt(message)
  print (result)
elif user_request == 'encode':
  result = encrypt(message)
  print (result)